### ISSUE TITLE
ElfsightEmbedSDK.createWidget does not work without app alias

### ISSUE THREAD

**Issue by yshyshkin** [elfsight/embed-sdk#39]
Hi Elfsight team,

According to the documentation, app alias option of the ElfsightEmbedSDK.createWidget function is optional:
```
const appAlias = 'instashow'; // optional. alias for specified application, displays the popup if not specified
const callback = function(response) {
    // logic on
};

ElfsightEmbedSDK.createWidget(appAlias).then(callback);
```

However, if you try omiting that option like that `ElfsightEmbedSDK.createWidget().then(function() {})`, SDK will trigger an error:
```
embed-sdk.js:8 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__H')
    at p (embed-sdk.js:8:20934)
    at b (embed-sdk.js:8:21507)
    at v (embed-sdk.js:8:21343)
    at Function.value (embed-sdk.js:23:14674)
    at embed-sdk.js:23:14959
    at new Promise (<anonymous>)
    at embed-sdk.js:23:14926
    at u (embed-sdk.js:8:58872)
    at Generator._invoke (embed-sdk.js:8:58660)
    at forEach.t.<computed> [as next] (embed-sdk.js:8:59295)
```

I have tried to pass null and '', but no luck.

Is there a way to open a popup with an application selection similar to one triggered by displayCreateButton via SDK?

Thank you,
Yevhen

**Comment by welcomemax** [comment]
Sorry for the long answer.

Couldn't reproduce issue with createWidget in dev build, but error might be with render the popup itself via preact in prod build.

You can also use the displayCatalog method

`ElfsightEmbedSDK.displayCatalog(document.querySelector('#elfsight-catalog-container'), (widget) => console.log('created widget', widget))`

It will work similar to createWidget without an argument, but instead of a popup you can embed its directory anywhere.
